FROM debian:bookworm-slim

WORKDIR /app

# Copy the native binary from the build stage
COPY target/helidon-photobook /app/helidon-photobook

# Run the application
ENTRYPOINT [ "sh", "-c", "/app/helidon-photobook ${JAVA_OPTS_APPEND}"]